---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
unzip("activity.zip")
activity <- read.csv("activity.csv")
activity$date <- as.Date(data$date)
activity_date <- aggregate(steps ~ date, data = data, sum, na.rm = TRUE)
```
## What is mean total number of steps taken per day?
```{r}
graph_1 <- hist(activity_date$steps, xlab= "Number Of Steps", main = "Total Steps Per Day")
mean(activity_date$steps, na.rm=TRUE)
```
## What is the average daily activity pattern?
```{r}
activity_date_mean <- aggregate(steps ~ interval, data = data, mean, na.rm = TRUE)
graph_2 <- plot(activity_date_mean$steps ~ activity_date_mean$interval, type = "l", 
                xlab = "Date", ylab = "Steps" , na.rm = TRUE)
```
## Imputing missing values
```{r}
sum(is.na(activity))
```
## Are there differences in activity patterns between weekdays and weekends?
```{r}
activity <- activity %>% mutate(dayofweek = weekdays(date))
head(activity)
activity$dayofweek[activity$dayofweek %in% c("Saturday","Sunday")] <- "weekend"
activity$dayofweek[activity$dayofweek != "weekend"] <- "weekday"
activity_interval <- aggregate(steps ~ interval + dayofweek, activity, mean)
library(ggplot2)
qplot(interval, steps, data = activity_interval, type = "l", geom=c("line"),
      xlab = "Interval", ylab = "Steps", main = "") +
        facet_wrap(~ dayofweek, ncol = 1)
```
Yes. 